# Generated by Django 3.1.2 on 2021-09-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Contract_type',
            field=models.CharField(blank=True, choices=[('Per.', 'Permanent'), ('Tem.', 'Temporaire')], default='Per.', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Date Birth of the Driver'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cni',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='National Identity Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnss_registration_number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='CNSS Registration Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_licence_expiration_date',
            field=models.DateField(blank=True, verbose_name='Expiration Date for Driver Licence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_licence',
            field=models.ImageField(blank=True, help_text='Driver Licence Picture', upload_to='images/driver_licence/', verbose_name='Driver Licence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='glasses_certificat',
            field=models.ImageField(blank=True, help_text='Driver Glasses Certificat Picture', upload_to='images/driver_glasse_certificate/', verbose_name='Driver Glasse Certificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, help_text='Driver Identity Picture', upload_to='images/driver/', verbose_name='Driver Pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Driver Registration Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rib_bank',
            field=models.PositiveIntegerField(blank=True, verbose_name='RIB of the Driver Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Company website'),
        ),
    ]
