# Generated by Django 3.1.2 on 2021-09-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210908_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnss_registration_number',
            field=models.PositiveIntegerField(blank=True, verbose_name='CNSS Registration Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Driver Registration Number'),
        ),
    ]
