# Generated by Django 3.1.2 on 2021-09-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210908_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnss_registration_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CNSS Registration Number'),
        ),
    ]
