# Generated by Django 3.1.2 on 2021-11-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211030_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Last Name')),
                ('mobile', models.CharField(blank=True, max_length=150, verbose_name='Mobile Number')),
                ('mobile_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mobile Number')),
                ('landline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Landline Number')),
                ('Contract_type', models.CharField(blank=True, choices=[('Per.', 'Permanent'), ('Tem.', 'Temporaire')], default='Per.', max_length=4)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name')),
                ('ice', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ICE of the Company')),
                ('website', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Company website')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Client Account',
                'verbose_name_plural': 'Clients Accounts',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client', verbose_name='Customer'),
        ),
    ]
