# Generated by Django 3.1.2 on 2021-11-20 03:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211106_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.CreateModel(
            name='FreeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=50, verbose_name="Nom d'Adresse")),
                ('postcode', models.CharField(max_length=50, verbose_name='Code-Postale')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Adresse Ligne 1')),
                ('address_line_2', models.CharField(max_length=255, verbose_name='Adresse Ligne 2')),
                ('address_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('town_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city', verbose_name='Ville')),
                ('town_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Free Address',
                'verbose_name_plural': 'Free Addresses',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Nom de la Société')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Mobile Number')),
                ('website', models.CharField(blank=True, max_length=150, verbose_name='Site Web')),
                ('natonale_transp_autorization', models.CharField(blank=True, max_length=30, null=True, verbose_name='Autorisation de Transport National N°')),
                ('internatonale_transp_commissionnaire', models.CharField(blank=True, max_length=30, null=True, verbose_name='Commissionnaire de Transport International N°')),
                ('comerce_registre', models.IntegerField(blank=True, default=1, null=True, verbose_name='Registre de Comerce N°')),
                ('cnss_matricule', models.IntegerField(blank=True, default=1, null=True, verbose_name='CNSS matricule N°')),
                ('patente', models.IntegerField(blank=True, default=1, null=True, verbose_name='Patente N°')),
                ('identifiant_fiscale', models.IntegerField(blank=True, default=1, null=True, verbose_name='Identifiant Fiscal N°')),
                ('ice', models.IntegerField(blank=True, default=1, null=True, verbose_name='ICE N°')),
                ('rib', models.CharField(blank=True, max_length=120, null=True, verbose_name='RIB')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_adresse', to='account.freeaddress')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank')),
                ('bank_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Banque_adresse', to='account.freeaddress')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company'),
        ),
    ]
