# Generated by Django 3.1.2 on 2021-11-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_freeaddress_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ICE N°'),
        ),
    ]
