# Generated by Django 3.1.2 on 2021-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211120_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='images/company/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('op', 'Operator'), ('ad', 'Administration'), ('dr', 'Driver')], max_length=2),
        ),
    ]
