# Generated by Django 3.1.2 on 2021-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20211120_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_instructions',
            field=models.CharField(blank=True, default="Pas d'instructions", max_length=255, null=True, verbose_name='Instructions de Livraison'),
        ),
    ]
