# Generated by Django 3.1.2 on 2021-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20211121_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('op', 'Operator'), ('ad', 'Administration'), ('dr', 'Driver')], default='op', max_length=2),
        ),
    ]
