# Generated by Django 3.1.2 on 2021-08-14 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Make Company logo', upload_to='images/make/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
