# Generated by Django 3.1.2 on 2021-09-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='total_paid',
        ),
    ]
