# Generated by Django 3.1.2 on 2021-11-01 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20211030_2338'),
        ('deliveries', '0002_auto_20211031_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='destination_post_code',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='full_name_reciever',
        ),
        migrations.AddField(
            model_name='delivery',
            name='operation_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='desired pickup date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_address', to='account.address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user', to=settings.AUTH_USER_MODEL, verbose_name='delivery_user'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_pickup',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_pickup', to=settings.AUTH_USER_MODEL, verbose_name='user_pickup'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_reciever',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever', to=settings.AUTH_USER_MODEL, verbose_name='user_reciever'),
        ),
    ]
