# Generated by Django 3.1.2 on 2021-11-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_is_active'),
        ('deliveries', '0004_auto_20211103_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user', to='account.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_pickup',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_pickup', to='account.client', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_reciever',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever', to='account.client', verbose_name='user_reciever'),
        ),
    ]
