# Generated by Django 3.1.2 on 2021-11-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211105_0459'),
        ('deliveries', '0005_auto_20211104_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='user_pickup',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_pickup', to='account.client', verbose_name='donneur'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_reciever',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever', to='account.client', verbose_name='receveur'),
        ),
    ]
