# Generated by Django 3.1.2 on 2021-11-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_auto_20211105_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='user',
        ),
    ]
