# Generated by Django 3.1.2 on 2021-11-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_remove_deliverydetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='document',
            field=models.FileField(blank=True, help_text='Delivery Documets', null=True, upload_to='documents/deliveries_documents/', verbose_name='Delivery Certificates'),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Approximative distance '),
        ),
    ]
