# Generated by Django 3.1.2 on 2021-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_auto_20211109_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Approximative distance '),
        ),
    ]
