# Generated by Django 3.1.2 on 2021-11-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_auto_20211109_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='geo_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='google_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='google_duration_value',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distance Approximative '),
        ),
    ]
