# Generated by Django 3.1.2 on 2021-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_auto_20211118_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed Delivery'),
        ),
    ]
