# Generated by Django 3.1.2 on 2021-11-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_delivery_confirmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryDetails',
            new_name='OperationDetails',
        ),
    ]
