# Generated by Django 3.1.2 on 2021-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_auto_20211123_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='boxes_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre des Boites'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='boxes_volume',
            field=models.PositiveIntegerField(default=0, verbose_name='Volume des Boites'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='boxes_wight',
            field=models.PositiveIntegerField(default=1, verbose_name='Poids de Boites'),
        ),
    ]
