# Generated by Django 3.1.2 on 2021-11-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_auto_20211125_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='document',
        ),
        migrations.CreateModel(
            name='DeliveryDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, help_text='Delivery Documets', null=True, upload_to='documents/deliveries_documents/', verbose_name='Delivery Certificates')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='deliveries.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Documents',
                'verbose_name_plural': 'Deliveries Documents',
                'ordering': ('-created_at', 'delivery'),
            },
        ),
    ]
