# Generated by Django 3.1.2 on 2021-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_auto_20211125_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='billing_status',
            field=models.BooleanField(default=False, verbose_name='Status de la Facturation'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_key',
            field=models.CharField(max_length=200, verbose_name='Numero de Livraison'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.BooleanField(default=False, verbose_name='Status de Livraison'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice',
            field=models.BooleanField(default=False, verbose_name='Facturation'),
        ),
    ]
